### ISSUE TITLE
NoSuchMethodError on javax.portlet.PortletContext.getContainerRuntimeOptions while starting my server

### ISSUE THREAD

**Issue by astik** [nilsga/maven-jetty-pluto-embedded#6]
At server startup, I've got a stacktrace :

[INFO] Started Jetty Server
[INFO] Starting scanner at interval of 3 seconds.
Exception in thread "Timer-1" java.lang.NoSuchMethodError: javax.portlet.PortletContext.getContainerRuntimeOptions()Ljava/util/Enumeration;
    at org.apache.pluto.container.impl.AbstractPortletConfigImpl.<init>(AbstractPortletConfigImpl.java:67)
    at org.apache.pluto.driver.container.DriverPortletConfigImpl.<init>(DriverPortletConfigImpl.java:38)
    at org.apache.pluto.driver.container.PortletContextManager.register(PortletContextManager.java:139)
    at org.apache.pluto.container.driver.PortletServlet.attemptRegistration(PortletServlet.java:192)
    at org.apache.pluto.container.driver.PortletServlet$1.run(PortletServlet.java:166)
    at java.util.TimerThread.mainLoop(Timer.java:512)
    at java.util.TimerThread.run(Timer.java:462)

Have you ever got this problem ? I'm thinking of a dependency issue with my portlet ...

Could you share on github a simple hello world project to see how everything work ? Thanks in advance.

**Comment by astik** [comment]
FYI, I'm working with portlet 2, so I'm using the 2_0_BRANCH branch.

**Comment by nilsga** [comment]
Yeah, probably something wrong with the classpath. Check the runtime
classpath by running with 'mvn -X' and see if you have conflicting
versions of the portlet API in the classpath.

Nils-H

On Thu, Sep 8, 2011 at 11:45 AM, Romain Gonord
reply@reply.github.com
wrote:

**Comment by astik** [comment]
Everything runs with portlet-api 2.0, I can't see anything talking about duplicate portlet-api.
Do you have any "hello world" project using your plugin ? (nothing fancy, just a basic one, i'll try to make it work and if it succeeds, i'll try to make it work with spring-mvc 3)

**Comment by nilsga** [comment]
Can you provide the output of mvn -X when running the plugin? What do you mean it's working with portlet 2.0?

**Comment by nilsga** [comment]
I used to have a Spring MVC sample. I'll see if I can find it.

**Comment by astik** [comment]
> What do you mean it's working with portlet 2.0?
> That just means that I'm using with your 2.0 branch (JSR286) =)

Here is one of my output : http://pastebin.com/xSR0yZ4a
Thanks for your help

**Comment by astik** [comment]
Clean my local repository and now it's ok .. don't know which dependency failed me =/

**Comment by nilsga** [comment]
That's good news :) Sorry for not getting back to you. Completely
forgot about it...

Regards,

Nils-Helge Garli Hegvik

On Wed, Sep 21, 2011 at 11:46 AM, Romain Gonord
reply@reply.github.com
wrote:
